### ISSUE TITLE
"this.getSegment is not a function" error in console when using coloredLine

### ISSUE THREAD

**Issue by nac0n** [blacklabel/multicolor_series#50]
First of; We're using:

```
Angular: 16.2.16
highcharts: 11.3.0
highcharts-angular: 4.0.1
highcharts-multicolor-series: (from 2.2.7 to) 3.1.0
```

After upgrading from angular 15 to 16. We get this error starting from angular 16 (and dependencies that belong to it, as seen above in the version list).

```
this.getSegment is not a function

15849/</drawGraph/<@http://localhost:4300/vendor.js:86410:41
drawGraph@http://localhost:4300/vendor.js:86409:20
render@http://localhost:4300/vendor.js:93418:203
redraw@http://localhost:4300/vendor.js:93424:32
32012/</</redraw/<@http://localhost:4300/vendor.js:94334:46
redraw@http://localhost:4300/vendor.js:94333:61
32012/</</setExtremes/<@http://localhost:4300/vendor.js:90361:91
```

If we set "type" of the series to "line", the problem goes away. So our suspicion is that there's an issue in the multicolor series code that doesn't go together with what we personally have.

We don't believe it's an import issue as if we remove these lines from the importing angular module;

```Typescript
import MulticolorSeries from "highcharts-multicolor-series";
MulticolorSeries(Highcharts);
```

We instead get an `highcharts #17` error saying `the module 'coloredLine' can't be found` if import is removed.

**Error**: `Highcharts error # 17: www.highcharts.com/errors/17/?missingModuleFor=coloredline - missingModuleFor: coloredline`

Any help is appreciated, to help us move forward.

**Comment by nac0n** [comment]
This looks like a problem in our project, as i created a Stackblitz project and it seems to work fine.

**Comment by pharandemahesh** [comment]
hi @nac0n ,

We are facing the exact same issue.
Can you tell us, how you fixed it?
